# Generated by Django 2.0 on 2018-01-11 19:44

from django.db import migrations, models
import django.utils.timezone
import sortedm2m.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('photologue', '0010_auto_20160105_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
                ('title', models.CharField(max_length=250, unique=True, verbose_name='title')),
                ('slug', models.SlugField(help_text='A "slug" is a unique URL-friendly title for an object.', max_length=250, unique=True, verbose_name='title slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_public', models.BooleanField(default=True, help_text='Public categories will be displayed in the default views.', verbose_name='is public')),
                ('photos', sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='categorie', to='photologue.Photo', verbose_name='photos')),
                ('sites', models.ManyToManyField(blank=True, to='sites.Site', verbose_name='sites')),
            ],
        ),
    ]
